package adventofcode2016_test

import (
	"fmt"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

type KeyPad struct {
	buttons  [][]string
	position Coordinates // 0, 0 is upper-left (y is inverted)
}

var phoneKeyPadLayout = [][]string{
	[]string{"1", "2", "3"},
	[]string{"4", "5", "6"},
	[]string{"7", "8", "9"},
}
var phoneKeyPadStart = Coordinates{1, 1}

func NewPhoneKeyPad() *KeyPad {
	return &KeyPad{phoneKeyPadLayout, phoneKeyPadStart}
}

var starKeyPadLayout = [][]string{
	[]string{"", "", "1", "", ""},
	[]string{"", "2", "3", "4", ""},
	[]string{"5", "6", "7", "8", "9"},
	[]string{"", "A", "B", "C", ""},
	[]string{"", "", "D", "", ""},
}
var starKeyPadStart = Coordinates{0, 2}

func NewStarKeyPad() *KeyPad {
	return &KeyPad{starKeyPadLayout, starKeyPadStart}
}

var keyPadMoveMap = map[byte]Coordinates{
	"U"[0]: Coordinates{0, -1},
	"R"[0]: Coordinates{1, 0},
	"D"[0]: Coordinates{0, 1},
	"L"[0]: Coordinates{-1, 0},
}

func (self *KeyPad) move(move byte) {
	direction := keyPadMoveMap[move]

	self.position.x += direction.x
	if self.position.x < 0 || self.position.x >= len(self.buttons[0]) || self.number() == "" {
		self.position.x -= direction.x
	}

	self.position.y += direction.y
	if self.position.y < 0 || self.position.y >= len(self.buttons) || self.number() == "" {
		self.position.y -= direction.y
	}
}

func (self KeyPad) number() string {
	return self.buttons[self.position.y][self.position.x]
}

func (self *KeyPad) code(instructions []string) []string {
	code := make([]string, len(instructions))
	for j, instruction := range instructions {
		for _, move := range []byte(instruction) {
			self.move(move)
		}
		code[j] = self.number()
	}
	return code
}

var _ = Describe("Day2", func() {
	Describe("KeyPad", func() {
		It("follows instructions and emits a code", func() {
			keypad := NewPhoneKeyPad()
			instructions := []string{
				"ULL",
				"RRDDD",
				"LURDL",
				"UUUUD",
			}
			Expect(keypad.code(instructions)).To(Equal([]string{"1", "9", "8", "5"}))
		})

		It("follows instructions and emits a code", func() {
			keypad := NewStarKeyPad()
			instructions := []string{
				"ULL",
				"RRDDD",
				"LURDL",
				"UUUUD",
			}
			Expect(keypad.code(instructions)).To(Equal([]string{"5", "D", "B", "3"}))
		})
	})

	Describe("the puzzle", func() {
		instructions := []string{
			"DDDURLURURUDLDURRURULLRRDULRRLRLRURDLRRDUDRUDLRDUUDRRUDLLLURLUURLRURURLRLUDDURUULDURDRUUDLLDDDRLDUULLUDURRLUULUULDLDDULRLDLURURUULRURDULLLURLDRDULLULRRRLRLRULLULRULUUULRLLURURDLLRURRUUUDURRDLURUURDDLRRLUURLRRULURRDDRDULLLDRDDDDURURLLULDDULLRLDRLRRDLLURLRRUDDDRDLLRUDLLLLRLLRUDDLUUDRLRRRDRLRDLRRULRUUDUUDULLRLUDLLDDLLDLUDRURLULDLRDDLDRUDLDDLDDDRLLDUURRUUDLLULLRLDLUURRLLDRDLRRRRUUUURLUUUULRRUDDUDDRLDDURLRLRLLRRUDRDLRLDRRRRRRUDDURUUUUDDUDUDU",
			"RLULUULRDDRLULRDDLRDUURLRUDDDUULUUUDDRDRRRLDUURDURDRLLLRDDRLURLDRRDLRLUURULUURDRRULRULDULDLRRDDRLDRUDUDDUDDRULURLULUDRDUDDDULRRRURLRRDLRDLDLLRLUULURLDRURRRLLURRRRRLLULRRRDDLRLDDUULDLLRDDRLLUUDRURLRULULRLRUULUUUUUDRURLURLDDUDDLRDDLDRRLDLURULUUDRDLULLURDLLLRRDRURUDDURRLURRDURURDLRUDRULUULLDRLRRDRLDDUDRDLLRURURLUDUURUULDURUDULRLRDLDURRLLDRDUDRUDDRLRURUDDLRRDLLLDULRRDRDRRRLURLDLURRDULDURUUUDURLDLRURRDRULLDDLLLRUULLLLURRRLLLDRRUDDDLURLRRRDRLRDLUUUDDRULLUULDURLDUUURUDRURUDRDLRRLDRURRLRDDLLLULUDDUULDURLRUDRDDD",
			"RDDRUDLRLDDDRLRRLRRLUULDRLRUUURULRRLUURLLLRLULDDLDLRLULULUUDDDRLLLUDLLRUDURUDDLLDUDLURRULLRDLDURULRLDRLDLDRDDRUDRUULLLLRULULLLDDDULUUDUUDDLDRLRRDLRLURRLLDRLDLDLULRLRDLDLRLUULLDLULRRRDDRUULDUDLUUUUDUDRLUURDURRULLDRURUDURDUULRRULUULULRLDRLRLLRRRLULURLUDULLDRLDRDRULLUUUDLDUUUDLRDULRDDDDDDDDLLRDULLUDRDDRURUDDLURRUULUURURDUDLLRRRRDUDLURLLURURLRDLDUUDRURULRDURDLDRUDLRRLDLDULRRUDRDUUDRLURUURLDLUDLLRDDRDU",
			"LLDDDDLUDLLDUDURRURLLLLRLRRLDULLURULDULDLDLLDRRDLUDRULLRUUURDRLLURDDLLUDDLRLLRDDLULRLDDRURLUDRDULLRUDDLUURULUUURURLRULRLDLDDLRDLDLLRUURDLUDRRRDDRDRLLUDDRLDRLLLRULRDLLRLRRDDLDRDDDUDUDLUULDLDUDDLRLDUULRULDLDULDDRRLUUURUUUDLRDRULDRRLLURRRDUDULDUDUDULLULLULULURLLRRLDULDULDLRDDRRLRDRLDRLUDLLLUULLRLLRLDRDDRUDDRLLDDLRULLLULRDDDLLLDRDLRULDDDLULURDULRLDRLULDDLRUDDUDLDDDUDRDRULULDDLDLRRDURLLRLLDDURRLRRULLURLRUDDLUURULULURLRUDLLLUDDURRLURLLRLLRRLDULRRUDURLLDDRLDLRRLULUULRRUURRRDULRLRLRDDRDULULUUDULLLLURULURRUDRLL",
			"UULLULRUULUUUUDDRULLRLDDLRLDDLULURDDLULURDRULUURDLLUDDLDRLUDLLRUURRUDRLDRDDRRLLRULDLLRUUULLLDLDDULDRLRURLDRDUURLURDRUURUULURLRLRRURLDDDLLDDLDDDULRUDLURULLDDRLDLUDURLLLLLRULRRLLUDRUURLLURRLLRDRLLLRRDDDRRRDLRDRDUDDRLLRRDRLRLDDDLURUUUUULDULDRRRRLUDRLRDRUDUDDRULDULULDRUUDUULLUDULRLRRURDLDDUDDRDULLUURLDRDLDDUURULRDLUDDLDURUDRRRDUDRRDRLRLULDRDRLRLRRUDLLLDDDRURDRLRUDRRDDLDRRLRRDLUURLRDRRUDRRDLDDDLRDDLRDUUURRRUULLDDDLLRLDRRLLDDRLRRRLUDLRURULLDULLLUDLDLRLLDDRDRUDLRRDDLUU",
		}

		It("star 1", func() {
			keypad := NewPhoneKeyPad()
			fmt.Println(keypad.code(instructions))
		})

		It("star 2", func() {
			keypad := NewStarKeyPad()
			fmt.Println(keypad.code(instructions))
		})
	})
})
